# Generated by Django 5.0.6 on 2026-05-27 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('CORPORATE_TRAVEL', 'Corporate Travel')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Indirect Emissions (Energy)'), ('SCOPE_3', 'Scope 3 - Other Indirect Emissions')], max_length=20)),
                ('category', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('co2_emissions_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emissions', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.datasource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emissions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.organization')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='emissions.organization'),
        ),
        migrations.CreateModel(
            name='RawDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='emissions.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='emissions.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'status'], name='emissions_e_organiz_a7c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_date'], name='emissions_e_activit_c89ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['scope'], name='emissions_e_scope_63e497_idx'),
        ),
    ]
